ARG base=ghcr.io/bootcrew/arch-bootc:latest
ARG bootc=ghcr.io/bootcrew/arch-bootc:latest
FROM $base as base

FROM $bootc as signer
RUN --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/usr/lib/sysimage/cache/pacman pacman -Sy sbsigntools systemd-ukify --needed --noconfirm

FROM signer as kernel
COPY scripts/uki-build.sh /uki-build.sh
RUN --mount=type=bind,from=base,target=/target \
    --network=none \
    --mount=type=secret,id=secureboot_key \
    --mount=type=secret,id=secureboot_cert \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/var/tmp \
    sh /uki-build.sh

FROM base
COPY --from=kernel /boot/*.efi /boot/EFI/Linux/
LABEL containers.bootc=sealed